env:
  es6: true
  browser: true
  commonjs: true

extends: ['htmlacademy/es6', 'plugin:react/recommended']

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 10
  sourceType: module

plugins: ['react']

rules:
  {"react/prop-types": 0}

settings:
  react:
    version: '17'
