env:
  es2017: true
  browser: true

extends: ['htmlacademy/react', 'plugin:react/recommended']

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module

plugins: ['react', 'import']

rules:
  {
    'jsx-quotes': [2, 'prefer-single'],
    'react/prop-types': 0,
    'import/order': [
      'error',
      {
        groups: [ "builtin", "external", "parent", "sibling", "index"],
        alphabetize: {
          order: 'asc',
        },
      },
    ],
  }

settings:
  react:
    version: '17'
